version: 2.1
# ???????????????????????????????????????????????

# orbs /// workflows:

jobs:
  test:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            pytest
      - run:
          name: Lint the code
          command: |
            flake8 .
  build_image:
      docker:
      - image: circleci/python:3.9
      steps:
        - checkout
        - setup_remote_docker

        - run:
            name: Build docker image
            command: |
            docker build -t  image_for_lettings_oc .
            docker login --username $DOCKERHUB_LOGIN --password $DOCKERHUB_PASSWORD    --password-stdin
            docker tag $DOCKER_LOGIN/$DOCKER_REPO:???? # docker_repo var

#        - run:
#            name: docker push
#            command: docker push
#deploy_heroku:
#  docker:
#    - image: circleci/python:3.9


  # docker image
  #docker login
  #docker tag
  # docker push

  #deploy heroku

workflows:
  version: 2
  test_and_build_image:
    jobs:
      - test
      - build_image