version: 2.1
# ???????????????????????????????????????????????
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            pytest
      - run:
          name: Lint the code
          command: |
            flake8 .
