version: 2.1
# ???????????????????????????????????????????????

# orbs /// workflows:

jobs:
  test:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            pytest
      - run:
          name: Lint the code
          command: |
            flake8 .
  build_image:
      docker:
      - image: circleci/python:3.8
        auth:
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
      steps:
        - checkout
        - setup_remote_docker

        - run:
            name: Build docker image

            command: |
              docker build -t  image_for_lettings_oc .
              echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
              docker pull 1youcef/oc-lettings:$CIRCLE_SHA1

              docker tag $CIRCLE_SHA1 1youcef/oc-lettings:$CIRCLE_SHA1
              docker push 1youcef/oc-lettings:$CIRCLE_SHA1

#
#deploy_heroku:
#  docker:
#    - image: circleci/python:3.9


  #deploy heroku

workflows:
  version: 2
  test_and_build_image:
    jobs:
      - test
      - build_image